create database proyectojsp_tecnm;

use proyectojsp_tecnm;

/*--------------------CREACION DE LAS TABLAS--------------------*/
CREATE TABLE `proyectojsp_tecnm`.`usuario` (
`id` INT NOT NULL AUTO_INCREMENT ,
`prefijo` VARCHAR(255) NOT NULL,
`nombre` VARCHAR(255) NOT NULL ,
`apellidopat` VARCHAR(255) NOT NULL ,
`apellidomat` VARCHAR(255) NOT NULL ,
`usuario` VARCHAR(255) NOT NULL ,
`contrasena` VARCHAR(255) NOT NULL ,
`rol` INT(1) NOT NULL ,
PRIMARY KEY (`id`)
);

CREATE TABLE `proyectojsp_tecnm`.`materia` (
`id_materia` INT NOT NULL AUTO_INCREMENT ,
`clave` VARCHAR (255) NOT NULL ,
`nombre` VARCHAR (255) NOT NULL ,
`semestre` INT NOT NULL ,
`carrera` VARCHAR (255) NOT NULL ,
`creditos` INT NOT NULL ,
`horas_t` INT NOT NULL ,
`horas_p` INT NOT NULL ,
PRIMARY KEY (`id_materia`)
);

CREATE TABLE `proyectojsp_tecnm`.`horario` (
`id_horario` INT NOT NULL AUTO_INCREMENT,
`clave` INT NOT NULL, `grupo` VARCHAR(255) NULL,
`periodo` BOOLEAN NULL,
`numero_estudiantes` INT NULL,
`salon` VARCHAR(255) NULL,
`lunes` VARCHAR(255) NULL,
`martes` VARCHAR(255) NULL,
`miercoles` VARCHAR(255) NULL,
`jueves` VARCHAR(255) NULL,
`viernes` VARCHAR(255) NULL,
PRIMARY KEY (id_horario) 
);
/*--------------------INSERCIONES DE LAS TABLAS--------------------*/
INSERT INTO usuario (rol, prefijo, nombre, apellidopat, apellidomat, usuario, contrasena)
VALUES	(1, "Ingeniero", "Antonio", "Águila", "Reyes", "aguila", "12345"),
		(2, "Doctora", "María del Rosario", "Baltazar", "Flores", "baltazar", "123"),
		(2, "Ingeniero", "José Gerardo", "Carpio", "Flores", "carpiof", "123"),
		(2, "Doctor", "Juan Martín", "Carpio", "Valadez", "carpiov", "123"),
		(2, "Licenciada", "Elizabeth", "Castellanos", "Nolasco", "nolasco", "123"),
		(2, "Ingeniera", "María Patricia", "Castillo", "Martínez", "castillo", "123"),
		(2, "Ingeniero", "Luis Roberto", "Gallegos", "Muñoz", "gallegos", "123"),
		(2, "Ingeniero", "Domingo", "García", "Ornelas", "domingo", "123"),
		(2, "Ingeniero", "Hector Federico", "Godínez", "Cabrera", "godinez", "123"),
		(2, "Ingeniera", "Laura Patricia", "Guevara", "Rangel", "laurap", "123"),
		(2, "Ingeniero", "Luis Eduardo", "Gutiérrez", "Ayala", "ayala", "123"),
		(2, "Ingeniera", "Angélica Benita", "Hernández", "Carranza", "benita", "123"),
		(2, "Ingeniera", "Laura", "Juárez", "Guerra", "laura", "123"),
		(2, "Ingeniero", "Carlos Rafael", "Levy", "Rojas", "levy", "123"),
		(2, "Ingeniero", "Eugenio Conrado", "Marín", "González", "conrado", "123"),
		(2, "Ingeniera", "Ana Columba Zurita", "Martínez", "Aguilar", "columba", "123"),
		(2, "Ingeniero", "José Elias", "Martínez", "Arias", "elias", "123"),
		(2, "Ingeniera", "Edna Militza", "Martínez", "Prado", "militza", "123"),
		(2, "Ingeniero", "Juan Pablo", "Murillo", "Ruiz", "murillo", "123"),
		(2, "Licenciada", "Angélica María", "Ortiz", "Gaucín", "gaucin", "123"),
		(2, "Licenciado", "Héctor José", "Puga", "Soberanes", "pugas", "123"),
		(2, "Licenciada", "Irma de Jesús", "Ramírez", "Álvarez", "irma", "123"),
		(2, "Maestra en Ciencias", "Martha Alicia", "Rocha", "Sánchez", "martha", "123"),
		(2, "Ingeniera", "Luz del Carmen", "Ruiz", "Gaytan", "luzcarmen", "123"),
		(2, "Ingeniera", "Ruth", "Saéz de Nanclarez", "Rodríguez", "ruth", "123"),
		(2, "Maestra", "Ma. Concepción Rocío", "Sánchez", "Cano", "maconceptionr", "123"),
		(2, "Ingeniera", "Ma. Concepción", "Sandoval", "Solis", "maconcepcion", "123"),
		(2, "Ingeniero", "Cirino", "Silva", "Tovar", "cirino", "123"),
		(2, "Ingeniero", "José Luis Fernando", "Suárez", "y Gómez", "suarezygomez", "123"),
		(2, "Ingeniero", "Rubén", "Trujillo", "Corona", "trujillo", "123");
		
INSERT INTO materia (clave, nombre, semestre, carrera, creditos, horas_t, horas_p)
VALUES	("ACF-0901", "Cálculo Diferencial", 1, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("AED-1285", "Fundamentos de Programación", 1, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("ACA-0907", "Taller de Ética", 1, "Ingenieria en sistemas computacionales", 4, 0, 4),
		("AEF-1041", "Matemáticas Discretas", 1, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("SCH-1024", "Taller de Administración", 1, "Ingenieria en sistemas computacionales", 4, 1, 3),
		("ACC-0906", "Fundamentos de Investigación", 1, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("ACF-0902", "Cálculo Integral", 2, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("AED-1286", "Programación Orientada a Objetos", 2, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("AEC-1008", "Contabilidad Financiera", 2, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("AEC-1058", "Quimica", 2, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("ACF-0903", "Álgebra Lineal", 2, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("AEF-1052", "Probabilidad y Estadística", 2, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("ACF-0904", "Cálculo Vectorial", 3, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("AED-1026", "Estructura de Datos", 3, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCC-1005", "Cultura Empresarial", 3, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCC-1013", "Investigación de Operaciones", 3, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("ACD-0908", "Desarrollo Sustentable", 3, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("SCF-1006", "Física General", 3, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("ACF-0905", "Ecuaciones Diferenciales", 4, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("SCC-1017", "Métodos Numéricos", 4, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCD-1027", "Tópicos Avanzados de Programación", 4, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("AEF-1031", "Fundamentos de Base de Datos", 4, "Ingenieria en sistemas computacionales", 5, 3, 2),
		("SCD-1022", "Simulación", 4, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCD-1018", "Principios Eléctricos y Aplicaciones Digitales", 4, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCC-1010", "Graficación", 5, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("AEC-1034", "Fundamentos de Telecomunicaciones", 5, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("AEC-1061", "Sistemas Operativos", 5, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCA-1025", "Taller de Base de Datos", 5, "Ingenieria en sistemas computacionales", 4, 0, 2),
		("SCC-1007", "Fundamentos de Ingeniería de Software", 5, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCD-1003", "Arquitectura de Computadoras", 5, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCD-1015", "Lenguajes y Autómatas I", 6, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCD-1021", "Redes de Computadoras", 6, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCA-1026", "Taller de Sistemas Operativos", 6, "Ingenieria en sistemas computacionales", 4, 0, 4),
		("SCB-1001", "Administración de Base de Datos", 6, "Ingenieria en sistemas computacionales", 5, 1, 4),
		("SCD-1011", "Ingeniería de Software", 6, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCC-1014", "Lenguaje de Interfaz", 6, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCD-1016", "Lenguajes y Autómatas II", 7, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("SCD-1004", "Conmutación y Enrutamiento en Redes de Datos", 7, "Ingenieria en sistemas computacionales", 5, 2, 3),
		("ACA-0909", "Taller de Investigación I", 7, "Ingenieria en sistemas computacionales", 4, 0, 4),
		("SCG-1009", "Gestión de Proyectos de Software", 7, "Ingenieria en sistemas computacionales", 6, 3, 3),
		("SCC-1023", "Sistemas Programables", 7, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCC-1019", "Programación Lógica y Funcional", 8, "Ingenieria en sistemas computacionales", 4, 2, 2),
		("SCA-1002", "Administración de Redes", 8, "Ingenieria en sistemas computacionales", 4, 0, 4),
		("ACA-0910", "Taller de Investigación II", 8, "Ingenieria en sistemas computacionales", 4, 0, 4),
		("AEB-1055", "Programación Web", 8, "Ingenieria en sistemas computacionales", 5, 1, 4),
		("SCC-1012", "Inteligencia Artificial", 9, "Ingenieria en sistemas computacionales", 4, 2, 2);

